# Generated by Django 3.0.5 on 2020-05-11 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('city', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('Singer', 'Singer'), ('Baglama-Player', 'Baglama-Player'), ('Guitar-Player', 'Guitar-Player'), ('Violin-Player', 'Violin-Player'), ('Acordion-Player', 'Acordion-Player'), ('Chor-Chef', 'Chor-Chef')], default='Singer', max_length=20)),
                ('image', models.ImageField(default='post_list/profile_images/default.jpg', upload_to='post_list/profile_images')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
