# Generated by Django 3.1.4 on 2020-12-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postlist', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created_date',)},
        ),
    ]
