# Generated by Django 3.0.5 on 2020-05-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='books/pdfs')),
                ('cover', models.FileField(blank=True, null=True, upload_to='books/cover')),
            ],
        ),
    ]
